// Countries: ISO 3166 code (what Wi-Fi's regulatory domain takes), name, and
// the mobile country codes (MCC) its networks use (what the carrier list is
// keyed on). Generated from pbakondy/mcc-mnc-list (MIT; data from
// Wikipedia's mobile country code articles), national networks only. An MCC
// shared with territories (310-316 with Puerto Rico, Guam...) belongs to the
// country with the most networks on it; the territories keep their own entry
// for Wi-Fi, with no MCC of their own.

export interface Country {
  iso: string
  name: string
  mcc: string[]
}

export const COUNTRIES: Country[] = [
  { iso: 'AF', name: "Afghanistan", mcc: ['412'] },
  { iso: 'AL', name: "Albania", mcc: ['276'] },
  { iso: 'DZ', name: "Algeria", mcc: ['603'] },
  { iso: 'AS', name: "American Samoa (United States of America)", mcc: ['544'] },
  { iso: 'AD', name: "Andorra", mcc: ['213'] },
  { iso: 'AO', name: "Angola", mcc: ['631'] },
  { iso: 'AI', name: "Anguilla (United Kingdom)", mcc: ['365'] },
  { iso: 'AG', name: "Antigua and Barbuda", mcc: ['344'] },
  { iso: 'AR', name: "Argentina", mcc: ['722'] },
  { iso: 'AM', name: "Armenia", mcc: ['283'] },
  { iso: 'AW', name: "Aruba (Kingdom of the Netherlands)", mcc: ['363'] },
  { iso: 'AT', name: "Austria", mcc: ['232'] },
  { iso: 'AZ', name: "Azerbaijan", mcc: ['400'] },
  { iso: 'BS', name: "Bahamas", mcc: ['364'] },
  { iso: 'BH', name: "Bahrain", mcc: ['426'] },
  { iso: 'BD', name: "Bangladesh", mcc: ['470'] },
  { iso: 'BB', name: "Barbados", mcc: ['342'] },
  { iso: 'BY', name: "Belarus", mcc: ['257'] },
  { iso: 'BE', name: "Belgium", mcc: ['206'] },
  { iso: 'BZ', name: "Belize", mcc: ['702'] },
  { iso: 'BJ', name: "Benin", mcc: ['616'] },
  { iso: 'BM', name: "Bermuda", mcc: ['350'] },
  { iso: 'BT', name: "Bhutan", mcc: ['402'] },
  { iso: 'BO', name: "Bolivia", mcc: ['736'] },
  { iso: 'BA', name: "Bosnia and Herzegovina", mcc: ['218'] },
  { iso: 'BW', name: "Botswana", mcc: ['652'] },
  { iso: 'BR', name: "Brazil", mcc: ['724'] },
  { iso: 'VG', name: "British Virgin Islands (United Kingdom)", mcc: ['348'] },
  { iso: 'BN', name: "Brunei", mcc: ['528'] },
  { iso: 'BG', name: "Bulgaria", mcc: ['284'] },
  { iso: 'BF', name: "Burkina Faso", mcc: ['613'] },
  { iso: 'BI', name: "Burundi", mcc: ['642'] },
  { iso: 'KH', name: "Cambodia", mcc: ['456'] },
  { iso: 'CM', name: "Cameroon", mcc: ['624'] },
  { iso: 'CA', name: "Canada", mcc: ['302'] },
  { iso: 'CV', name: "Cape Verde", mcc: ['625'] },
  { iso: 'KY', name: "Cayman Islands (United Kingdom)", mcc: ['346'] },
  { iso: 'CF', name: "Central African Republic", mcc: ['623'] },
  { iso: 'TD', name: "Chad", mcc: ['622'] },
  { iso: 'CL', name: "Chile", mcc: ['730'] },
  { iso: 'CN', name: "China", mcc: ['460'] },
  { iso: 'CO', name: "Colombia", mcc: ['732'] },
  { iso: 'KM', name: "Comoros", mcc: ['654'] },
  { iso: 'CG', name: "Congo", mcc: ['629'] },
  { iso: 'CK', name: "Cook Islands (Pacific Ocean)", mcc: ['548'] },
  { iso: 'CR', name: "Costa Rica", mcc: ['712'] },
  { iso: 'HR', name: "Croatia", mcc: ['219'] },
  { iso: 'CU', name: "Cuba", mcc: ['368'] },
  { iso: 'CY', name: "Cyprus", mcc: ['280'] },
  { iso: 'CZ', name: "Czechia", mcc: ['230'] },
  { iso: 'CD', name: "DR Congo", mcc: ['630'] },
  { iso: 'DK', name: "Denmark (Kingdom of Denmark)", mcc: ['238'] },
  { iso: 'DJ', name: "Djibouti", mcc: ['638'] },
  { iso: 'DM', name: "Dominica", mcc: ['366'] },
  { iso: 'DO', name: "Dominican Republic", mcc: ['370'] },
  { iso: 'TL', name: "East Timor", mcc: ['514'] },
  { iso: 'EC', name: "Ecuador", mcc: ['740'] },
  { iso: 'EG', name: "Egypt", mcc: ['602'] },
  { iso: 'SV', name: "El Salvador", mcc: ['706'] },
  { iso: 'GQ', name: "Equatorial Guinea", mcc: ['627'] },
  { iso: 'ER', name: "Eritrea", mcc: ['657'] },
  { iso: 'EE', name: "Estonia", mcc: ['248'] },
  { iso: 'SZ', name: "Eswatini", mcc: ['653'] },
  { iso: 'ET', name: "Ethiopia", mcc: ['636'] },
  { iso: 'FK', name: "Falkland Islands (United Kingdom)", mcc: ['750'] },
  { iso: 'FO', name: "Faroe Islands (Kingdom of Denmark)", mcc: ['288'] },
  { iso: 'FM', name: "Federated States of Micronesia", mcc: ['550'] },
  { iso: 'FJ', name: "Fiji", mcc: ['542'] },
  { iso: 'FI', name: "Finland", mcc: ['244'] },
  { iso: 'FR', name: "France", mcc: ['208'] },
  { iso: 'GF', name: "French Guiana (France)", mcc: ['340', '742'] },
  { iso: 'PF', name: "French Polynesia (France)", mcc: ['547'] },
  { iso: 'GA', name: "Gabon", mcc: ['628'] },
  { iso: 'GM', name: "Gambia", mcc: ['607'] },
  { iso: 'GE', name: "Georgia", mcc: ['282'] },
  { iso: 'DE', name: "Germany", mcc: ['262'] },
  { iso: 'GH', name: "Ghana", mcc: ['620'] },
  { iso: 'GI', name: "Gibraltar (United Kingdom)", mcc: ['266'] },
  { iso: 'GR', name: "Greece", mcc: ['202'] },
  { iso: 'GL', name: "Greenland (Kingdom of Denmark)", mcc: ['290'] },
  { iso: 'GD', name: "Grenada", mcc: ['352'] },
  { iso: 'GU', name: "Guam (United States of America)", mcc: [] },
  { iso: 'GT', name: "Guatemala", mcc: ['704'] },
  { iso: 'GG', name: "Guernsey (United Kingdom)", mcc: [] },
  { iso: 'GN', name: "Guinea", mcc: ['611'] },
  { iso: 'GW', name: "Guinea-Bissau", mcc: ['632'] },
  { iso: 'GY', name: "Guyana", mcc: ['738'] },
  { iso: 'HT', name: "Haiti", mcc: ['372'] },
  { iso: 'HN', name: "Honduras", mcc: ['708'] },
  { iso: 'HK', name: "Hong Kong", mcc: ['454'] },
  { iso: 'HU', name: "Hungary", mcc: ['216'] },
  { iso: 'IS', name: "Iceland", mcc: ['274'] },
  { iso: 'IN', name: "India", mcc: ['404', '405'] },
  { iso: 'ID', name: "Indonesia", mcc: ['510'] },
  { iso: 'IR', name: "Iran", mcc: ['432'] },
  { iso: 'IQ', name: "Iraq", mcc: ['418'] },
  { iso: 'IE', name: "Ireland", mcc: ['272'] },
  { iso: 'IM', name: "Isle of Man (United Kingdom)", mcc: [] },
  { iso: 'IL', name: "Israel", mcc: ['425'] },
  { iso: 'IT', name: "Italy", mcc: ['222'] },
  { iso: 'CI', name: "Ivory Coast", mcc: ['612'] },
  { iso: 'JM', name: "Jamaica", mcc: ['338'] },
  { iso: 'JP', name: "Japan", mcc: ['440', '441'] },
  { iso: 'JE', name: "Jersey (United Kingdom)", mcc: [] },
  { iso: 'JO', name: "Jordan", mcc: ['416'] },
  { iso: 'KZ', name: "Kazakhstan", mcc: ['401'] },
  { iso: 'KE', name: "Kenya", mcc: ['639'] },
  { iso: 'KI', name: "Kiribati", mcc: ['545'] },
  { iso: 'XK', name: "Kosovo", mcc: ['221'] },
  { iso: 'KW', name: "Kuwait", mcc: ['419'] },
  { iso: 'KG', name: "Kyrgyzstan", mcc: ['437'] },
  { iso: 'LA', name: "Laos", mcc: ['457'] },
  { iso: 'LV', name: "Latvia", mcc: ['247'] },
  { iso: 'LB', name: "Lebanon", mcc: ['415'] },
  { iso: 'LS', name: "Lesotho", mcc: ['651'] },
  { iso: 'LR', name: "Liberia", mcc: ['618'] },
  { iso: 'LY', name: "Libya", mcc: ['606'] },
  { iso: 'LI', name: "Liechtenstein", mcc: ['295'] },
  { iso: 'LT', name: "Lithuania", mcc: ['246'] },
  { iso: 'LU', name: "Luxembourg", mcc: ['270'] },
  { iso: 'MO', name: "Macau (People's Republic of China)", mcc: ['455'] },
  { iso: 'MG', name: "Madagascar", mcc: ['646'] },
  { iso: 'MW', name: "Malawi", mcc: ['650'] },
  { iso: 'MY', name: "Malaysia", mcc: ['502'] },
  { iso: 'MV', name: "Maldives", mcc: ['472'] },
  { iso: 'ML', name: "Mali", mcc: ['610'] },
  { iso: 'MT', name: "Malta", mcc: ['278'] },
  { iso: 'MH', name: "Marshall Islands", mcc: ['551'] },
  { iso: 'MR', name: "Mauritania", mcc: ['609'] },
  { iso: 'MU', name: "Mauritius", mcc: ['617'] },
  { iso: 'MX', name: "Mexico", mcc: ['334'] },
  { iso: 'MD', name: "Moldova", mcc: ['259'] },
  { iso: 'MC', name: "Monaco", mcc: ['212'] },
  { iso: 'MN', name: "Mongolia", mcc: ['428'] },
  { iso: 'ME', name: "Montenegro", mcc: ['297'] },
  { iso: 'MS', name: "Montserrat (United Kingdom)", mcc: ['354'] },
  { iso: 'MA', name: "Morocco", mcc: ['604'] },
  { iso: 'MZ', name: "Mozambique", mcc: ['643'] },
  { iso: 'MM', name: "Myanmar", mcc: ['414'] },
  { iso: 'NA', name: "Namibia", mcc: ['649'] },
  { iso: 'NR', name: "Nauru", mcc: ['536'] },
  { iso: 'NP', name: "Nepal", mcc: ['429'] },
  { iso: 'NL', name: "Netherlands (Kingdom of the Netherlands)", mcc: ['204'] },
  { iso: 'NC', name: "New Caledonia (France)", mcc: ['546'] },
  { iso: 'NZ', name: "New Zealand", mcc: ['530'] },
  { iso: 'NI', name: "Nicaragua", mcc: ['710'] },
  { iso: 'NE', name: "Niger", mcc: ['614'] },
  { iso: 'NG', name: "Nigeria", mcc: ['621'] },
  { iso: 'NU', name: "Niue", mcc: ['555'] },
  { iso: 'NF', name: "Norfolk Island", mcc: ['505'] },
  { iso: 'KP', name: "North Korea", mcc: ['467'] },
  { iso: 'MK', name: "North Macedonia", mcc: ['294'] },
  { iso: 'MP', name: "Northern Mariana Islands (United States of America)", mcc: [] },
  { iso: 'NO', name: "Norway", mcc: ['242'] },
  { iso: 'OM', name: "Oman", mcc: ['422'] },
  { iso: 'PK', name: "Pakistan", mcc: ['410'] },
  { iso: 'PW', name: "Palau", mcc: ['552'] },
  { iso: 'PS', name: "Palestine", mcc: [] },
  { iso: 'PA', name: "Panama", mcc: ['714'] },
  { iso: 'PG', name: "Papua New Guinea", mcc: ['537'] },
  { iso: 'PY', name: "Paraguay", mcc: ['744'] },
  { iso: 'PE', name: "Peru", mcc: ['716'] },
  { iso: 'PH', name: "Philippines", mcc: ['515'] },
  { iso: 'PL', name: "Poland", mcc: ['260'] },
  { iso: 'PT', name: "Portugal", mcc: ['268'] },
  { iso: 'PR', name: "Puerto Rico", mcc: ['330'] },
  { iso: 'QA', name: "Qatar", mcc: ['427'] },
  { iso: 'RO', name: "Romania", mcc: ['226'] },
  { iso: 'RU', name: "Russia", mcc: ['250'] },
  { iso: 'RW', name: "Rwanda", mcc: ['635'] },
  { iso: 'SH', name: "Saint Helena, Ascension and Tristan da Cunha", mcc: ['658'] },
  { iso: 'KN', name: "Saint Kitts and Nevis", mcc: ['356'] },
  { iso: 'LC', name: "Saint Lucia", mcc: ['358'] },
  { iso: 'PM', name: "Saint Pierre and Miquelon (France)", mcc: ['308'] },
  { iso: 'VC', name: "Saint Vincent and the Grenadines", mcc: ['360'] },
  { iso: 'WS', name: "Samoa", mcc: ['549'] },
  { iso: 'SM', name: "San Marino", mcc: ['292'] },
  { iso: 'SA', name: "Saudi Arabia", mcc: ['420'] },
  { iso: 'SN', name: "Senegal", mcc: ['608'] },
  { iso: 'RS', name: "Serbia", mcc: ['220'] },
  { iso: 'SC', name: "Seychelles", mcc: ['633'] },
  { iso: 'SL', name: "Sierra Leone", mcc: ['619'] },
  { iso: 'SG', name: "Singapore", mcc: ['525'] },
  { iso: 'SK', name: "Slovakia", mcc: ['231'] },
  { iso: 'SI', name: "Slovenia", mcc: ['293'] },
  { iso: 'SB', name: "Solomon Islands", mcc: ['540'] },
  { iso: 'SO', name: "Somalia", mcc: ['637'] },
  { iso: 'ZA', name: "South Africa", mcc: ['655'] },
  { iso: 'KR', name: "South Korea", mcc: ['450'] },
  { iso: 'SS', name: "South Sudan", mcc: ['659'] },
  { iso: 'ES', name: "Spain", mcc: ['214'] },
  { iso: 'LK', name: "Sri Lanka", mcc: ['413'] },
  { iso: 'SD', name: "Sudan", mcc: ['634'] },
  { iso: 'SR', name: "Suriname", mcc: ['746'] },
  { iso: 'SE', name: "Sweden", mcc: ['240'] },
  { iso: 'CH', name: "Switzerland", mcc: ['228'] },
  { iso: 'SY', name: "Syria", mcc: ['417'] },
  { iso: 'ST', name: "São Tomé and Príncipe", mcc: ['626'] },
  { iso: 'TW', name: "Taiwan", mcc: ['466'] },
  { iso: 'TJ', name: "Tajikistan", mcc: ['436'] },
  { iso: 'TZ', name: "Tanzania", mcc: ['640'] },
  { iso: 'TH', name: "Thailand", mcc: ['520'] },
  { iso: 'TG', name: "Togo", mcc: ['615'] },
  { iso: 'TK', name: "Tokelau", mcc: ['554'] },
  { iso: 'TO', name: "Tonga", mcc: ['539'] },
  { iso: 'TT', name: "Trinidad and Tobago", mcc: ['374'] },
  { iso: 'TN', name: "Tunisia", mcc: ['605'] },
  { iso: 'TR', name: "Turkey", mcc: ['286'] },
  { iso: 'TM', name: "Turkmenistan", mcc: ['438'] },
  { iso: 'TC', name: "Turks and Caicos Islands", mcc: ['376'] },
  { iso: 'TV', name: "Tuvalu", mcc: ['553'] },
  { iso: 'UG', name: "Uganda", mcc: ['641'] },
  { iso: 'UA', name: "Ukraine", mcc: ['255'] },
  { iso: 'AE', name: "United Arab Emirates", mcc: ['424'] },
  { iso: 'GB', name: "United Kingdom", mcc: ['234', '235'] },
  { iso: 'US', name: "United States", mcc: ['310', '311', '312', '313', '314', '315', '316'] },
  { iso: 'VI', name: "United States Virgin Islands (United States of America)", mcc: [] },
  { iso: 'UY', name: "Uruguay", mcc: ['748'] },
  { iso: 'UZ', name: "Uzbekistan", mcc: ['434'] },
  { iso: 'VU', name: "Vanuatu", mcc: ['541'] },
  { iso: 'VE', name: "Venezuela", mcc: ['734'] },
  { iso: 'VN', name: "Vietnam", mcc: ['452'] },
  { iso: 'WF', name: "Wallis and Futuna", mcc: ['543'] },
  { iso: 'YE', name: "Yemen", mcc: ['421'] },
  { iso: 'ZM', name: "Zambia", mcc: ['645'] },
  { iso: 'ZW', name: "Zimbabwe", mcc: ['648'] },
]

const BY_ISO = new Map(COUNTRIES.map((c) => [c.iso, c]))
const BY_MCC = new Map(COUNTRIES.flatMap((c) => c.mcc.map((m) => [m, c] as const)))

export const countryByIso = (iso: string | null | undefined): Country | null => (iso ? (BY_ISO.get(iso.toUpperCase()) ?? null) : null)
export const countryByMcc = (mcc: string | null | undefined): Country | null => (mcc ? (BY_MCC.get(mcc) ?? null) : null)

/**
 * The country to offer first, most trustworthy source first:
 *  1. the network the SIM is registered on - where the router physically is;
 *  2. the Wi-Fi country already set, unless it is a factory placeholder
 *     ("US" is what OpenWrt ships, "00" is "world");
 *  3. this browser's region ("en-PH" -> PH);
 *  4. the Wi-Fi country as it is, placeholder or not.
 */
export function guessCountry(o: { mcc?: string | null; wifi?: string | null; locale?: string | null }): Country | null {
  const fromSim = countryByMcc(o.mcc)
  if (fromSim) return fromSim
  const wifi = countryByIso(o.wifi)
  if (wifi && wifi.iso !== 'US') return wifi
  const region = o.locale?.match(/[-_]([A-Za-z]{2})\b/)?.[1]
  return countryByIso(region) ?? wifi
}
